/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projet;

import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.* ; 
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.border.Border;

/**
 *
 * @author ASUS
 */
public class csolde extends javax.swing.JFrame {
      private String nom ; 

    public void setNom(String nom) {
        this.nom = nom;
    }
    private String image ; 

    public void setImage(String image) {
        this.image = image;
    }
    
      

    /**
     * Creates new form csolde
     */
  

    public JLabel getLblsolde() {
        return lblsolde;
            
    }

    public csolde() {
        initComponents();
        Border boder = BorderFactory.createMatteBorder(3, 3, 3, 3, Color.green);
        lblsolde.setBorder(boder);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblsolde = new javax.swing.JLabel();
        btndeconnexion = new javax.swing.JButton();
        btnretour = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Votre solde est ");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 27, 237, 60));

        lblsolde.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblsolde.setText("jLabel2");
        getContentPane().add(lblsolde, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 152, 384, 158));

        btndeconnexion.setBackground(new java.awt.Color(102, 255, 204));
        btndeconnexion.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btndeconnexion.setText("deconnexion");
        btndeconnexion.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btndeconnexionMouseMoved(evt);
            }
        });
        btndeconnexion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btndeconnexionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btndeconnexionMouseExited(evt);
            }
        });
        btndeconnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeconnexionActionPerformed(evt);
            }
        });
        getContentPane().add(btndeconnexion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 200, 60));

        btnretour.setBackground(new java.awt.Color(102, 255, 204));
        btnretour.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnretour.setText("retour");
        btnretour.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnretourMouseMoved(evt);
            }
        });
        btnretour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnretourMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnretourMouseExited(evt);
            }
        });
        btnretour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnretourActionPerformed(evt);
            }
        });
        getContentPane().add(btnretour, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 190, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndeconnexionMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndeconnexionMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btndeconnexionMouseMoved

    private void btndeconnexionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndeconnexionMouseEntered
        btndeconnexion.setBackground(new Color(255,51,0));

    }//GEN-LAST:event_btndeconnexionMouseEntered

    private void btndeconnexionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndeconnexionMouseExited
        btndeconnexion.setBackground(new Color(102,255,204));

    }//GEN-LAST:event_btndeconnexionMouseExited

    private void btndeconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeconnexionActionPerformed
        this.dispose();
        JOptionPane.showMessageDialog(null, "a bientot ", "au revoir ", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_btndeconnexionActionPerformed

    private void btnretourMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnretourMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btnretourMouseMoved

    private void btnretourMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnretourMouseEntered
        btnretour.setBackground(new Color(255,51,0));
    }//GEN-LAST:event_btnretourMouseEntered

    private void btnretourMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnretourMouseExited
        btnretour.setBackground(new Color(102,255,204));

    }//GEN-LAST:event_btnretourMouseExited

    private void btnretourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnretourActionPerformed
        liste liste1=new liste();
       // liste1.setVisible(true);
        //liste1.setLocationRelativeTo(null);
        liste1.getLblbienvenu().setText(nom);
    int width = 138;    //width of the image
           int height = 103;   //height of the image
           BufferedImage imo = null;
           
           try
             {
                File input_file = new File("C:\\Users\\ASUS\\OneDrive\\Documents\\NetBeansProjects\\projet\\src\\images\\"+image); //image file path
                imo = new BufferedImage(width, height,
                                     BufferedImage.TYPE_INT_ARGB);
                imo = ImageIO.read(input_file);
                System.out.println("Reading complete.");
                  liste1.setVisible(true);
                  liste1.setLocationRelativeTo(null);
             }
        catch(IOException ex)
          {
          ex.printStackTrace(); 
    }
           liste1.getLblimage().setIcon(new ImageIcon(imo));
           liste1.setIndex(image);
 
               this.dispose(); 

        
        
        
        System.out.println(nom);

    }//GEN-LAST:event_btnretourActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
           /* for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }*/
           UIManager.setLookAndFeel("com.jtattoo.plaf.mint.MintLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(csolde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(csolde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(csolde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(csolde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new csolde().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndeconnexion;
    private javax.swing.JButton btnretour;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblsolde;
    // End of variables declaration//GEN-END:variables
}
