/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projet;

import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class formulaire_virement extends javax.swing.JFrame {
private String nom ; 

    public void setNom(String nom) {
        this.nom = nom;
    }
    private  String image ;  

    public void setImage(String image) {
        this.image = image;
    }
    
    
    
    
    /**
     * Creates new form formulaire_virement
     */
    public formulaire_virement() {
        initComponents();
    }
     private boolean verifuser(){
    PreparedStatement ps ;
    ResultSet rs ; 
    boolean userexist= false ; 
    String query = "SELECT cin FROM users.client WHERE cin = ?  " ; 
    try
    {
    ps=ConnectionBd.getconnection().prepareStatement(query) ;
                ps.setString(1,cdest.getText());
          
              rs=ps.executeQuery();
              if(rs.next()){
                  userexist=true;  
              }
    }catch(Exception ex){
        JOptionPane.showMessageDialog(null, "cin n existe pas  ","erreur", JOptionPane.ERROR_MESSAGE);
    }
    return userexist ; 
}
     
     private boolean verifusere(){
    PreparedStatement ps ;
    ResultSet rs ; 
    boolean userexist= false ; 
    String query = "SELECT cin FROM users.client WHERE cin = ?  " ; 
    try
    {
    ps=ConnectionBd.getconnection().prepareStatement(query) ;
                ps.setString(1,tcin1.getText());
          
              rs=ps.executeQuery();
              if(rs.next()){
                  userexist=true;  
              }
    }catch(Exception ex){
        JOptionPane.showMessageDialog(null, "cin de l expéditeur  n existe pas  ","erreur", JOptionPane.ERROR_MESSAGE);
    }
    return userexist ; 
}
     
     
     
     
     
     
     private boolean checkpin(String s1){
         boolean pin =false ;
if(s1.equals("1234"))
    pin =true ;

return pin ;
    


     }
      private boolean checkemptyfields(){
      return (cdest.getText().equals("") ||cdest.getText().equals("")) ||tpinvr.getText().equals("")  ; 
    }
      
      
      private boolean soldeexist() {
          boolean soldeinsuff=false ; 
          
          
          
          
          return soldeinsuff;
      }
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cindest = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cdest = new javax.swing.JTextField();
        tpinvr = new javax.swing.JTextField();
        btnvirement = new javax.swing.JButton();
        btnretour = new javax.swing.JButton();
        btndeconnexion = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tmontantvr = new javax.swing.JTextField();
        tcin1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cindest.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cindest.setForeground(new java.awt.Color(255, 51, 0));
        cindest.setText("Cin de destinataire : ");
        getContentPane().add(cindest, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 240, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 0));
        jLabel3.setText("code pin");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 180, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setText("virement : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 240, 50));

        cdest.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(cdest, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 240, 40));

        tpinvr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(tpinvr, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 240, 40));

        btnvirement.setBackground(new java.awt.Color(0, 255, 102));
        btnvirement.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnvirement.setText("virement ");
        btnvirement.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnvirementMouseMoved(evt);
            }
        });
        btnvirement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnvirementMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnvirementMouseExited(evt);
            }
        });
        btnvirement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvirementActionPerformed(evt);
            }
        });
        getContentPane().add(btnvirement, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, 240, 110));

        btnretour.setBackground(new java.awt.Color(102, 255, 204));
        btnretour.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnretour.setText("retour");
        btnretour.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnretourMouseMoved(evt);
            }
        });
        btnretour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnretourMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnretourMouseExited(evt);
            }
        });
        btnretour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnretourActionPerformed(evt);
            }
        });
        getContentPane().add(btnretour, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 190, 60));

        btndeconnexion.setBackground(new java.awt.Color(102, 255, 204));
        btndeconnexion.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btndeconnexion.setText("deconnexion");
        btndeconnexion.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btndeconnexionMouseMoved(evt);
            }
        });
        btndeconnexion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btndeconnexionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btndeconnexionMouseExited(evt);
            }
        });
        btndeconnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeconnexionActionPerformed(evt);
            }
        });
        getContentPane().add(btndeconnexion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 200, 60));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 0));
        jLabel5.setText("Cin : ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 180, 50));

        tmontantvr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tmontantvr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tmontantvrKeyTyped(evt);
            }
        });
        getContentPane().add(tmontantvr, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 240, 40));

        tcin1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(tcin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 240, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnvirementMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnvirementMouseMoved

    }//GEN-LAST:event_btnvirementMouseMoved

    private void btnvirementMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnvirementMouseEntered
        btnvirement.setBackground(new Color(255,51,0));
    }//GEN-LAST:event_btnvirementMouseEntered

    private void btnvirementMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnvirementMouseExited
        btnvirement.setBackground(new Color(0,255,102));
    }//GEN-LAST:event_btnvirementMouseExited

    private void btnvirementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvirementActionPerformed
       String s1 =tpinvr.getText();
        if(checkemptyfields()){
             JOptionPane.showMessageDialog(null, "Svp syez sur que vous avez remplissé tous les champs  ", "champs manquant", JOptionPane.ERROR_MESSAGE);
        }
        
           else if (!checkpin(s1))
        JOptionPane.showMessageDialog(null, "pin erroné  ", "", JOptionPane.ERROR_MESSAGE);
           
        else if (!verifuser()) 
        JOptionPane.showMessageDialog(null, "cin de destinataire  n'existe pas   ", "", JOptionPane.ERROR_MESSAGE);
          else if (!verifusere()) 
        JOptionPane.showMessageDialog(null, "cin de l expéditeure  n'existe pas   ", "", JOptionPane.ERROR_MESSAGE);
        
        else {
            String montant= tmontantvr.getText();
        String cin= cdest.getText();
        
       float mtv= Float.parseFloat(montant) ;
        PreparedStatement ps1 ;
        ResultSet rs ; 
        String query = "SELECT solde FROM users.client WHERE cin = ?";
        try {
            ps1=ConnectionBd.getconnection().prepareStatement(query) ;
            ps1.setString(1,tcin1.getText() );
               rs=ps1.executeQuery() ; 
                float solde=-1;
             
            if(rs.next())
                 solde = Float.parseFloat(rs.getString(1)) ;
            if (mtv>solde) 
                JOptionPane.showMessageDialog(null, "impossible de faire l opération de virement solde insuffisant  ", "echec ", JOptionPane.ERROR_MESSAGE);
      
            else{
                 String montantr= tmontantvr.getText();
        PreparedStatement ps ;
        String queryr = "UPDATE users.client SET solde = solde-? WHERE cin= ? " ;
        try {
            ps=ConnectionBd.getconnection().prepareStatement(queryr) ;
            ps.setString(1, montant);
            ps.setString(2,tcin1.getText());
            if(ps.executeUpdate()!=0){
            }
            
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "connexion echoué  ", "", JOptionPane.ERROR_MESSAGE);
        }
        
        PreparedStatement ps2 ;
        String querydb = "UPDATE users.client SET solde = solde+? WHERE cin= ? " ;
        try {
            ps2=ConnectionBd.getconnection().prepareStatement(querydb) ;
            ps2.setString(1, tmontantvr.getText());
            ps2.setString(2,cdest.getText());
            if(ps2.executeUpdate()!=0){
                JOptionPane.showMessageDialog(null, "la modification  se fait avec succés  ", "succées", JOptionPane.PLAIN_MESSAGE);
            }
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "connexion echoué  ", "", JOptionPane.ERROR_MESSAGE);
        }
       
            }
            
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "connexion echoué  ", "", JOptionPane.ERROR_MESSAGE);
        }
        }
                
                
        
           
        

        
        
        
        
        
        
    }//GEN-LAST:event_btnvirementActionPerformed

    private void btnretourMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnretourMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btnretourMouseMoved

    private void btnretourMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnretourMouseEntered
        btnretour.setBackground(new Color(255,51,0));
    }//GEN-LAST:event_btnretourMouseEntered

    private void btnretourMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnretourMouseExited
        btnretour.setBackground(new Color(102,255,204));

    }//GEN-LAST:event_btnretourMouseExited

    private void btnretourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnretourActionPerformed
        liste liste1=new liste();
        //liste1.setVisible(true);
       // liste1.setLocationRelativeTo(null);
        liste1.getLblbienvenu().setText(nom);
      
        int width = 138;    //width of the image
           int height = 103;   //height of the image
           BufferedImage imo = null;
           
           try
             {
                File input_file = new File("C:\\Users\\ASUS\\OneDrive\\Documents\\NetBeansProjects\\projet\\src\\images\\"+image); //image file path
                imo = new BufferedImage(width, height,
                                     BufferedImage.TYPE_INT_ARGB);
                imo = ImageIO.read(input_file);
                System.out.println("Reading complete.");
                  liste1.setVisible(true);
                  liste1.setLocationRelativeTo(null);
             }
        catch(IOException ex)
          {
          ex.printStackTrace(); 
    }
           liste1.getLblimage().setIcon(new ImageIcon(imo));
           liste1.setIndex(image);
 
               this.dispose(); 
        
        
       this.dispose();
        System.out.println(nom);

    }//GEN-LAST:event_btnretourActionPerformed

    private void btndeconnexionMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndeconnexionMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btndeconnexionMouseMoved

    private void btndeconnexionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndeconnexionMouseEntered
        btndeconnexion.setBackground(new Color(255,51,0));

    }//GEN-LAST:event_btndeconnexionMouseEntered

    private void btndeconnexionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndeconnexionMouseExited
        btndeconnexion.setBackground(new Color(102,255,204));

    }//GEN-LAST:event_btndeconnexionMouseExited

    private void btndeconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeconnexionActionPerformed
        this.dispose();
        JOptionPane.showMessageDialog(null, "a bientot ", "au revoir ", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_btndeconnexionActionPerformed

    private void tmontantvrKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tmontantvrKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tmontantvrKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formulaire_virement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formulaire_virement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formulaire_virement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formulaire_virement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formulaire_virement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndeconnexion;
    private javax.swing.JButton btnretour;
    private javax.swing.JButton btnvirement;
    private javax.swing.JTextField cdest;
    private javax.swing.JLabel cindest;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField tcin1;
    private javax.swing.JTextField tmontantvr;
    private javax.swing.JTextField tpinvr;
    // End of variables declaration//GEN-END:variables
}
