/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projet;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author ASUS
 */
public class formulaire1 extends javax.swing.JFrame {
    private String cin ; 

    public void setCin(String cin) {
        this.cin = cin;
    }
private  String image ;  

    public void setImage(String image) {
        this.image = image;
    }
   
    
  

    /**
     * Creates new form formulaire1
     */
    public formulaire1() {
        initComponents();
    }
    private boolean checkemptyfields(){
      return (tcinr.getText().equals("") ||tmontantr.getText().equals("")) ||tpinr.getText().equals("")  ; 
    }
     
     private boolean verifuser(){
    PreparedStatement ps ;
    ResultSet rs ; 
    boolean userexist= false ; 
    String query = "SELECT cin FROM users.client WHERE cin = ?  " ; 
    try
    {
    ps=ConnectionBd.getconnection().prepareStatement(query) ;
                ps.setString(1,tcinr.getText());
          
              rs=ps.executeQuery();
              if(rs.next()){
                  userexist=true;  
              }
            
    }catch(Exception ex){
        JOptionPane.showMessageDialog(null, "cin n existe pas  ","erreur", JOptionPane.ERROR_MESSAGE);
    }
    return userexist ; 
}
 
     private boolean checkpin(String s1){
return (s1.equals("1234"));

     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tmontantr = new javax.swing.JTextField();
        tpinr = new javax.swing.JTextField();
        tcinr = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnretrais = new javax.swing.JButton();
        btndeconnexion = new javax.swing.JButton();
        btnretour = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setText("montant a retirer :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 240, 50));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 0));
        jLabel4.setText("Cin : ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 180, 50));

        tmontantr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tmontantr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tmontantrKeyTyped(evt);
            }
        });
        getContentPane().add(tmontantr, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 240, 40));

        tpinr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(tpinr, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 240, 40));

        tcinr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(tcinr, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 240, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 0));
        jLabel3.setText("code pin");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 180, 50));

        btnretrais.setBackground(new java.awt.Color(0, 255, 102));
        btnretrais.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnretrais.setText("retrait");
        btnretrais.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnretraisMouseMoved(evt);
            }
        });
        btnretrais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnretraisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnretraisMouseExited(evt);
            }
        });
        btnretrais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnretraisActionPerformed(evt);
            }
        });
        getContentPane().add(btnretrais, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 240, 100));

        btndeconnexion.setBackground(new java.awt.Color(102, 255, 204));
        btndeconnexion.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btndeconnexion.setText("deconnexion");
        btndeconnexion.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btndeconnexionMouseMoved(evt);
            }
        });
        btndeconnexion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btndeconnexionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btndeconnexionMouseExited(evt);
            }
        });
        btndeconnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeconnexionActionPerformed(evt);
            }
        });
        getContentPane().add(btndeconnexion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 200, 60));

        btnretour.setBackground(new java.awt.Color(102, 255, 204));
        btnretour.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnretour.setText("retour");
        btnretour.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnretourMouseMoved(evt);
            }
        });
        btnretour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnretourMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnretourMouseExited(evt);
            }
        });
        btnretour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnretourActionPerformed(evt);
            }
        });
        getContentPane().add(btnretour, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 190, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tmontantrKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tmontantrKeyTyped
        char key = evt.getKeyChar() ;
        if(!Character.isDigit(key)){
            evt.consume();
        }
    }//GEN-LAST:event_tmontantrKeyTyped

    private void btnretraisMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnretraisMouseMoved

    }//GEN-LAST:event_btnretraisMouseMoved

    private void btnretraisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnretraisMouseEntered
        btnretrais.setBackground(new Color(255,51,0));
    }//GEN-LAST:event_btnretraisMouseEntered

    private void btnretraisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnretraisMouseExited
        btnretrais.setBackground(new Color(0,255,102));
    }//GEN-LAST:event_btnretraisMouseExited

    private void btnretraisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnretraisActionPerformed
        String s1 =tpinr.getText();
        if(checkemptyfields()){
            JOptionPane.showMessageDialog(null, "Svp syez sur que vous avez remplissé tous les champs  ", "champs manquant", JOptionPane.ERROR_MESSAGE);
        }
              else if (!checkpin(s1))
        JOptionPane.showMessageDialog(null, "pin erroné  ", "", JOptionPane.ERROR_MESSAGE);
              
        else if (!verifuser())
        JOptionPane.showMessageDialog(null, "cin n existe pas   ", "", JOptionPane.ERROR_MESSAGE);
        
        else {
            String montant= tmontantr.getText();
        String cin= tcinr.getText();
        
       float mtv= Float.parseFloat(montant) ;
        PreparedStatement ps1 ;
        ResultSet rs ; 
        String query = "SELECT solde FROM users.client WHERE cin = ?";
        try {
            ps1=ConnectionBd.getconnection().prepareStatement(query) ;
            ps1.setString(1,tcinr.getText() );
               rs=ps1.executeQuery() ; 
                float solde=-1;
             
            if(rs.next())
                 solde = Float.parseFloat(rs.getString(1)) ;
            if (mtv>solde) 
                JOptionPane.showMessageDialog(null, "impossible de faire l opération de virement solde insuffisant  ", "echec ", JOptionPane.ERROR_MESSAGE);
            else {
               
        PreparedStatement ps ;
        String query1 = "UPDATE users.client SET solde = solde-? WHERE cin= ? " ;
  
            ps=ConnectionBd.getconnection().prepareStatement(query1) ;
            ps.setString(1, montant);
            ps.setString(2,tcinr.getText());
            if(ps.executeUpdate()!=0){
                JOptionPane.showMessageDialog(null, "la modification  se fait avec succés  ", "succées", JOptionPane.PLAIN_MESSAGE);
            }
            }
             
          }catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "connexion echoué  ", "", JOptionPane.ERROR_MESSAGE);
        }
        
        
        
        
        
   
            
        }

       

    }//GEN-LAST:event_btnretraisActionPerformed

    private void btndeconnexionMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndeconnexionMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btndeconnexionMouseMoved

    private void btndeconnexionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndeconnexionMouseEntered
        btndeconnexion.setBackground(new Color(255,51,0));
        
    }//GEN-LAST:event_btndeconnexionMouseEntered

    private void btndeconnexionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndeconnexionMouseExited
       btndeconnexion.setBackground(new Color(102,255,204));
        
    }//GEN-LAST:event_btndeconnexionMouseExited

    private void btndeconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeconnexionActionPerformed
        this.dispose(); 
        JOptionPane.showMessageDialog(null, "a bientot ", "au revoir ", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_btndeconnexionActionPerformed

    private void btnretourMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnretourMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btnretourMouseMoved

    private void btnretourMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnretourMouseEntered
       btnretour.setBackground(new Color(255,51,0));
    }//GEN-LAST:event_btnretourMouseEntered

    private void btnretourMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnretourMouseExited
         btnretour.setBackground(new Color(102,255,204));
    
    }//GEN-LAST:event_btnretourMouseExited

    private void btnretourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnretourActionPerformed
            liste liste1=new liste();
              // liste1.setVisible(true);
              //liste1.setLocationRelativeTo(null);
              liste1.getLblbienvenu().setText(cin);
              
                int width = 138;    //width of the image
           int height = 103;   //height of the image
           BufferedImage imo = null;
           
           try
             {
                File input_file = new File("C:\\Users\\ASUS\\OneDrive\\Documents\\NetBeansProjects\\projet\\src\\images\\"+image); //image file path
                imo = new BufferedImage(width, height,
                                     BufferedImage.TYPE_INT_ARGB);
                imo = ImageIO.read(input_file);
                System.out.println("Reading complete.");
                  liste1.setVisible(true);
                  liste1.setLocationRelativeTo(null);
             }
        catch(IOException ex)
          {
          ex.printStackTrace(); 
    }
           liste1.getLblimage().setIcon(new ImageIcon(imo));
           liste1.setIndex(image);
 
               this.dispose(); 
              
              
              
              
          
               
               
               
               System.out.println(cin);
        
        
    }//GEN-LAST:event_btnretourActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formulaire1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formulaire1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formulaire1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formulaire1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formulaire1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndeconnexion;
    private javax.swing.JButton btnretour;
    private javax.swing.JButton btnretrais;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField tcinr;
    private javax.swing.JTextField tmontantr;
    private javax.swing.JTextField tpinr;
    // End of variables declaration//GEN-END:variables
}
