/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet;

import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author ASUS
 */
public class inscription extends javax.swing.JFrame {

    private String NameCurrentImage;
     private String ExtensionCurrentImage;
    
    
    

    /**
     * Creates new form inscription
     */
    public inscription() {
        initComponents();
        
            Border boderpanel = BorderFactory.createMatteBorder(3, 3, 3, 3, Color.green);
       panelregistre.setBorder(boderpanel);
       Border boderlabel = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
       lblfermer.setBorder(boderlabel);
       lbreduit.setBorder(boderlabel);
  Border boderchamp = BorderFactory.createMatteBorder(3, 3, 3, 3, Color.white);
tnom.setBorder(boderchamp);
tprenom.setBorder(boderchamp);
tel.setBorder(boderchamp);
tpassword.setBorder(boderchamp);
tel.setBorder(boderchamp);
tpassword.setBorder(boderchamp);
    }
    private boolean checkemptyfields(){
        return (tnom.getText().equals("")||tprenom.getText().equals("")||String.valueOf(tpassword.getPassword()).equals("") || String.valueOf(tpassword1.getPassword()).equals("") ||tel.getText().equals("")||tel.equals("") ||lblimage.getText().equals("shema image ") || tcin.getText().equals("")  );
            
    }
private boolean verifpassword(String p1 , String p2){
        return p1.equals(p2); 
}
private boolean verifuser(){
    PreparedStatement ps ;
    ResultSet rs ; 
    boolean userexist= false ; 
    String query = "SELECT nom FROM users.client WHERE nom = ?  " ; 
    try
    {
    ps=ConnectionBd.getconnection().prepareStatement(query) ;
                ps.setString(1,tnom.getText());
              rs=ps.executeQuery();
              if(rs.next()){
                  userexist=true;
      JOptionPane.showMessageDialog(null, "ce utilisateur existe deja ","verifier", JOptionPane.ERROR_MESSAGE);  
              }
              
    }catch(Exception ex){
        ex.printStackTrace();
        JOptionPane.showMessageDialog(null, "connexion echoué"+ex.getMessage(),"erreur", JOptionPane.ERROR_MESSAGE);
    }
    return userexist ; 
}
  private String troncer(String a1){
  String extension  ="";
        int index = a1.lastIndexOf('.');
          if(index > 0) {
      extension = a1.substring(index + 1);
      System.out.println("File extension is " + extension);
    }
        
        return extension ; 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelregistre = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblfermer = new javax.swing.JLabel();
        lbreduit = new javax.swing.JLabel();
        a = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel8 = new javax.swing.JLabel();
        rbfemme = new javax.swing.JRadioButton();
        rbhomme = new javax.swing.JRadioButton();
        tnom = new javax.swing.JTextField();
        tprenom = new javax.swing.JTextField();
        lblcin = new javax.swing.JLabel();
        tel = new javax.swing.JTextField();
        btnimage = new javax.swing.JButton();
        lblimage = new javax.swing.JLabel();
        btninscription = new javax.swing.JButton();
        lblogin = new javax.swing.JLabel();
        tpassword1 = new javax.swing.JPasswordField();
        tpassword = new javax.swing.JPasswordField();
        tcin = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        temail2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelregistre.setBackground(new java.awt.Color(255, 51, 51));
        panelregistre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("inscription ");
        panelregistre.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 150, 30));

        lblfermer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblfermer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblfermer.setText("X");
        lblfermer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblfermerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblfermerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblfermerMouseExited(evt);
            }
        });
        panelregistre.add(lblfermer, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 20, 20));

        lbreduit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbreduit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbreduit.setText("-");
        lbreduit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbreduitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbreduitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbreduitMouseExited(evt);
            }
        });
        panelregistre.add(lbreduit, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 20, 20));

        getContentPane().add(panelregistre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 100));

        a.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        a.setText("genre :");
        getContentPane().add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 150, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("nom :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 120, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("prenom  : ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 120, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("mot de passe : ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 150, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("confirmer mot de passe : ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 240, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Tel  : ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 240, 40));
        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("image :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, 130, 40));

        buttonGroup1.add(rbfemme);
        rbfemme.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rbfemme.setText("femme ");
        rbfemme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbfemmeActionPerformed(evt);
            }
        });
        getContentPane().add(rbfemme, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 500, 150, -1));

        buttonGroup1.add(rbhomme);
        rbhomme.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rbhomme.setText("homme ");
        rbhomme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbhommeActionPerformed(evt);
            }
        });
        getContentPane().add(rbhomme, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, -1, -1));
        getContentPane().add(tnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 250, 30));
        getContentPane().add(tprenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 250, 30));

        lblcin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblcin.setText("cin :");
        getContentPane().add(lblcin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 240, 40));

        tel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telActionPerformed(evt);
            }
        });
        tel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telKeyTyped(evt);
            }
        });
        getContentPane().add(tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 250, 30));

        btnimage.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnimage.setText("selectionner image");
        btnimage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimageActionPerformed(evt);
            }
        });
        getContentPane().add(btnimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 560, 200, 30));

        lblimage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblimage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblimage.setText("shema image ");
        getContentPane().add(lblimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 390, 30));

        btninscription.setBackground(new java.awt.Color(255, 51, 0));
        btninscription.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btninscription.setText("inscription");
        btninscription.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btninscriptionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btninscriptionMouseExited(evt);
            }
        });
        btninscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninscriptionActionPerformed(evt);
            }
        });
        getContentPane().add(btninscription, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 640, 160, 60));

        lblogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblogin.setForeground(new java.awt.Color(255, 51, 0));
        lblogin.setText(" >> vous n'avez pas compte , inscrivez vous");
        lblogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbloginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbloginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbloginMouseExited(evt);
            }
        });
        getContentPane().add(lblogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 720, 320, -1));

        tpassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpassword1ActionPerformed(evt);
            }
        });
        getContentPane().add(tpassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 250, 30));

        tpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(tpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 250, 30));

        tcin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcinActionPerformed(evt);
            }
        });
        getContentPane().add(tcin, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 250, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("email : ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 240, 40));

        temail2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temail2ActionPerformed(evt);
            }
        });
        getContentPane().add(temail2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 250, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbhommeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbhommeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbhommeActionPerformed

    private void rbfemmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbfemmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbfemmeActionPerformed

    private void lblfermerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblfermerMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblfermerMouseClicked

    private void lblfermerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblfermerMouseEntered
        Border br = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        lblfermer.setBorder(br);
        lblfermer.setForeground(Color.white);
    }//GEN-LAST:event_lblfermerMouseEntered

    private void lblfermerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblfermerMouseExited

        Border br1 = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        lblfermer.setBorder(br1);
        lblfermer.setForeground(Color.black);
    }//GEN-LAST:event_lblfermerMouseExited

    private void lbreduitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbreduitMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lbreduitMouseClicked

    private void lbreduitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbreduitMouseEntered

        Border br1 = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        lbreduit.setBorder(br1);
        lbreduit.setForeground(Color.white);
    }//GEN-LAST:event_lbreduitMouseEntered

    private void lbreduitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbreduitMouseExited
        Border br1 = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        lbreduit.setBorder(br1);
        lbreduit.setForeground(Color.black);

    }//GEN-LAST:event_lbreduitMouseExited

    private void telActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telActionPerformed

    private void btninscriptionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btninscriptionMouseEntered
        // TODO add your handling code here:
       btninscription.setBackground(new Color(0,255,204));

    }//GEN-LAST:event_btninscriptionMouseEntered

    private void btninscriptionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btninscriptionMouseExited
      btninscription.setBackground(new Color(0,255,102));

        
    }//GEN-LAST:event_btninscriptionMouseExited

    private void lbloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbloginMouseClicked
        login login = new login() ;
        login.setVisible(true);
        login.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_lbloginMouseClicked

    private void lbloginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbloginMouseEntered
        lblogin.setForeground(Color.white);
    }//GEN-LAST:event_lbloginMouseEntered

    private void lbloginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbloginMouseExited
        lblogin.setForeground(new Color(255,51,0));
    }//GEN-LAST:event_lbloginMouseExited

    private void btnimageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimageActionPerformed
JFileChooser chooser =new JFileChooser() ; 
FileNameExtensionFilter filtre= new FileNameExtensionFilter("Image","jpeg","jpg","png") ;
String cin=tcin.getText();
chooser.addChoosableFileFilter(filtre);
chooser.setDialogTitle("choisir ton image");
int filestate = chooser.showDialog(null, "OK") ;
if (filestate==JFileChooser.APPROVE_OPTION) {
   File selectedImage= chooser.getSelectedFile();
   NameCurrentImage = selectedImage.getName();// à modifier ceci pour recupere l'extension et no n pas le nom..
   ExtensionCurrentImage= troncer(NameCurrentImage) ;
   System.out.println(cin);
   NameCurrentImage=cin+"."+ExtensionCurrentImage ;
   
           
   String path =selectedImage.getAbsolutePath() ; 
   lblimage.setText(path);
  System.out.println(path);
  String npath= "C:\\Users\\ASUS\\OneDrive\\Documents\\NetBeansProjects\\projet\\src\\images\\"+NameCurrentImage ;
  
  String src = path ; 
        String dest = npath ;
        Path tmp = null; 
    try {
        tmp = Files.copy(Paths.get(src), Paths.get(dest));
    } catch (IOException ex) {
        Logger.getLogger(inscription.class.getName()).log(Level.SEVERE, null, ex);
        ex.printStackTrace();
    }
  
        if(tmp != null) 
        { 
            System.out.println("Fichier copié avec succès"); 
        } 
        else
        {
            System.out.println("Impossible de déplacer le fichier"); 
        } 
    
  
   
   
    
}


 
        
    }//GEN-LAST:event_btnimageActionPerformed

    private void btninscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninscriptionActionPerformed
     if(checkemptyfields()){
         JOptionPane.showMessageDialog(null, "Svp syez sur que vous avez remplissé tous les champs  ", "champs manquant", JOptionPane.ERROR_MESSAGE);
     }
     else {
         String nom =tnom.getText(); 
         String prenom = tprenom.getText(); 
         String motdepasse =String.valueOf(tpassword.getPassword()) ;
         String confmotdepasse = String.valueOf(tpassword1.getPassword()) ; 
         String telephone = String.valueOf(tel.getText()) ; 
         String email = tel.getText() ; 
         String genre = "homme" ; 
         String cin = String.valueOf(tcin.getText()) ; 
        
     
         if (rbfemme.isSelected())
             genre="femme" ;
         if (!verifpassword(motdepasse,confmotdepasse)) {
     JOptionPane.showMessageDialog(null, "les mots de passes ne sont pas identiques ","verifier les mots de passes ", JOptionPane.ERROR_MESSAGE);
    
      }
         else {
             PreparedStatement ps ; 
             String query = "INSERT INTO users.client(nom,prenom,motdepasse,tel,email,genre,image,cin)VALUES(?,?,?,?,?,?,?,? )" ; 
            try {
                ps=ConnectionBd.getconnection().prepareStatement(query) ;
                if (ps==null)
                    System.out.println("ps null ");
                
                ps.setString(1, nom);
                ps.setString(2, prenom);
                ps.setString(3, motdepasse);
                ps.setString(4, telephone);
                ps.setString(5, email);
                ps.setString(6, genre);
                 ps.setString(7, cin+"."+ExtensionCurrentImage)    ;            
                ps.setString(8, cin);
   
                
              /* try {
                   InputStream image = new FileInputStream(new File(lblimage.getText())) ; 
                   
                   ps.setBlob(7, image);
                }catch(Exception ex){
                    ex.printStackTrace();
              JOptionPane.showMessageDialog(null, "image manquante   ", "champs manquant", JOptionPane.ERROR_MESSAGE);
                }
                */
               // recupere un image avec son non et son extision 
                if(!verifuser()) {
                    if(ps.executeUpdate()!=0){
       JOptionPane.showMessageDialog(null, "l ajout se fait avec succés  ", "succées", JOptionPane.INFORMATION_MESSAGE);

                    }
                    else {
     JOptionPane.showMessageDialog(null, "l ajout ne se fait pas   ", "erreur", JOptionPane.ERROR_MESSAGE);

                    }  
                }
                
            } catch(Exception ex) {
                ex.printStackTrace();
         JOptionPane.showMessageDialog(null, "connetion ", "", JOptionPane.ERROR_MESSAGE);

            }
         }
        }
    }//GEN-LAST:event_btninscriptionActionPerformed

    private void tpassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpassword1ActionPerformed
        
        
        
    }//GEN-LAST:event_tpassword1ActionPerformed

    private void tpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpasswordActionPerformed

    private void tcinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcinActionPerformed

    private void telKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telKeyTyped
        char key = evt.getKeyChar() ; 
        if(!Character.isDigit(key)){
            evt.consume(); 
        }
       
        
    }//GEN-LAST:event_telKeyTyped

    private void temail2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temail2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_temail2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inscription().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a;
    private javax.swing.JButton btnimage;
    private javax.swing.JButton btninscription;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblcin;
    private javax.swing.JLabel lblfermer;
    private javax.swing.JLabel lblimage;
    private javax.swing.JLabel lblogin;
    private javax.swing.JLabel lbreduit;
    private javax.swing.JPanel panelregistre;
    private javax.swing.JRadioButton rbfemme;
    private javax.swing.JRadioButton rbhomme;
    private javax.swing.JTextField tcin;
    private javax.swing.JTextField tel;
    private javax.swing.JTextField temail2;
    private javax.swing.JTextField tnom;
    private javax.swing.JPasswordField tpassword;
    private javax.swing.JPasswordField tpassword1;
    private javax.swing.JTextField tprenom;
    // End of variables declaration//GEN-END:variables
}
